### ISSUE TITLE
Algunos recursos extras que podríamos utilizar

### ISSUE THREAD

**Issue by eddie-ruva** [hackerschoolmty/prework#1]
Creo que en el sitio de prework podríamos utilizar algunos recursos extras para que los estudiantes puedan llegar rápido a la información que deben conocer. Creo que de estos no esperaría que leyeran todo pero son lugares en los que podrían conocer lo suficiente como para cubrir lo que se pide. Espero comentarios para ver cuales piensan que se deben de quedar, como deberíamos de incluirlos, etc. 

**Patrones de diseño**
- http://blog.codinghorror.com/understanding-model-view-controller/
- https://www.youtube.com/watch?v=eTdVkgF_Slo

**HTML/CSS**
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element
- https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Introduction
- https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax
- https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity
- https://developer.mozilla.org/en-US/docs/Web/CSS/inheritance
- https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started

**JavaScript**
- http://www.codecademy.com/en/tracks/javascript
- https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/JavaScript_basics
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript

**Ruby**
- http://www.codecademy.com/tracks/ruby

**Git**
- http://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
- https://www.airpair.com/git/learn-git-basics

**Github**
- http://jahya.net/blog/git-vs-github/
- https://help.github.com/articles/set-up-git/
- https://help.github.com/articles/create-a-repo/
- https://help.github.com/articles/fork-a-repo/

**Command Line Interface**
- http://code.tutsplus.com/tutorials/the-command-line-is-your-best-friend--net-30362
- http://blog.teamtreehouse.com/introduction-to-the-mac-os-x-command-line
- https://www.udemy.com/linux-command-line-volume1/

**Comment by kurenn** [comment]
Esta buenisimo! agrego esas ligas en donde corresponda en el prework y les aviso!

**Comment by juanpabloe** [comment]
Todos están buenísimos @eddie-ruva, tiras el PR?

**Comment by edolopez** [comment]
@eddie-ruva que onda Eddie, se hizo el PR de esto?

**Comment by eddie-ruva** [comment]
@edolopez simon el buen @kurenn las agregó. Voy a cerrar el issue.
